# Generated by Django 2.1.3 on 2018-11-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfresco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actitivy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
