# Generated by Django 2.1.3 on 2018-11-25 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alfresco', '0002_auto_20181125_1713'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actitivy',
            new_name='Activity',
        ),
    ]
